const state={currentUser:null,sessionId:localStorage.getItem('askdata_session')||newSessionId(),runId:null,savedAnalysisId:null,currentDashboardId:null,dashboards:[],eventSource:null,result:null,quotaRemaining:null};
const $=id=>document.getElementById(id);
const labels={intent:'意图识别',schema:'Schema 检索',plan:'分析规划',sql_generate:'SQL 生成',sql_validate:'SQL 校验',sql_execute:'执行查询',analysis:'数据分析',run:'运行状态'};
function newSessionId(){return `session_${Date.now()}_${Math.random().toString(36).slice(2,8)}`}
function persist(){localStorage.setItem('askdata_session',state.sessionId)}
function escapeHtml(v){const d=document.createElement('div');d.textContent=v==null?'':String(v);return d.innerHTML}
function toast(message){const el=document.createElement('div');el.className='toast';el.textContent=message;document.body.append(el);setTimeout(()=>el.remove(),1800)}
function showQuota(quota,notify=true){if(!quota)return;const button=$('testerModeButton');const hint=$('quotaHint');if(quota.unlimited){state.quotaRemaining=Infinity;hint.textContent='测试模式 · 不限次数';button.textContent='✓ 测试模式';button.classList.add('active');hint.classList.remove('hidden');$('sendButton').disabled=Boolean(state.runId);if(notify)toast('测试模式已开启，不限提问次数');return}state.quotaRemaining=Number(quota.remaining);button.textContent='测试模式';button.classList.remove('active');hint.textContent=state.quotaRemaining>0?`公开体验剩余 ${state.quotaRemaining}/${quota.limit} 次`:`公开体验额度已用完`;hint.classList.remove('hidden');$('sendButton').disabled=state.quotaRemaining===0||Boolean(state.runId);if(notify)toast(state.quotaRemaining>0?`本次体验还可提问 ${state.quotaRemaining} 次`:`本次体验的 ${quota.limit} 次提问已使用完`)}
async function api(path,options={}){const testToken=sessionStorage.getItem('askdata_test_token');const response=await fetch(path,{credentials:'same-origin',...options,headers:{'Content-Type':'application/json',...(testToken?{'X-AskData-Test-Token':testToken}:{}),...(options.headers||{})}});if(!response.ok){let detail=`请求失败 (${response.status})`;try{const body=await response.json();detail=body.detail||detail}catch{}if(response.status===401&&path!=='/api/auth/login')showLogin();const error=new Error(detail);error.status=response.status;throw error}return response.status===204?null:response.json()}
async function toggleTesterMode(){const stored=sessionStorage.getItem('askdata_test_token');if(stored&&state.quotaRemaining===Infinity){sessionStorage.removeItem('askdata_test_token');state.quotaRemaining=null;await loadDataSourceStatus();toast('已退出测试模式');return}const token=window.prompt('请输入测试码（仅保存在当前浏览器标签页）');if(!token?.trim())return;try{const health=await api('/api/health',{headers:{'X-AskData-Test-Token':token.trim()}});if(!health.tester_mode)throw new Error('测试码不正确');sessionStorage.setItem('askdata_test_token',token.trim());await loadDataSourceStatus();toast('测试模式已开启，不限提问次数')}catch(error){sessionStorage.removeItem('askdata_test_token');toast(error.message||'无法开启测试模式')}}
function userInitials(user){const source=(user.display_name||user.email||'DA').trim();const parts=source.split(/\s+/).filter(Boolean);return (parts.length>1?parts.slice(0,2).map(part=>part[0]).join(''):source.slice(0,2)).toUpperCase()}
function showLogin(){state.currentUser=null;state.runId=null;state.savedAnalysisId=null;state.result=null;if(state.eventSource)state.eventSource.close();$('appShell').classList.add('auth-hidden');$('authScreen').classList.remove('hidden');$('loginPassword').value='';$('loginButton').disabled=false;$('loginButton').textContent='登录工作台';setTimeout(()=>$('loginEmail').focus(),50)}
function showApp(user){state.currentUser=user;$('authScreen').classList.add('hidden');$('appShell').classList.remove('auth-hidden');$('accountName').textContent=user.display_name||user.email;$('userAvatar').textContent=userInitials(user);$('loginError').classList.add('hidden');$('syncDataSourceButton').classList.toggle('hidden',!user.is_admin);resetView();loadConversations();loadSavedAnalyses();loadDashboards();loadDataSourceStatus()}
async function initializeAuth(){try{const data=await api('/api/auth/me');showApp(data.user)}catch{try{const data=await api('/api/auth/guest',{method:'POST'});showApp(data.user)}catch{showLogin()}}}
async function login(event){event.preventDefault();const button=$('loginButton');button.disabled=true;button.textContent='正在登录…';$('loginError').classList.add('hidden');try{const data=await api('/api/auth/login',{method:'POST',body:JSON.stringify({email:$('loginEmail').value.trim(),password:$('loginPassword').value})});showApp(data.user)}catch(error){$('loginError').textContent=error.message;$('loginError').classList.remove('hidden');button.disabled=false;button.textContent='登录工作台'}}
async function logout(){try{await api('/api/auth/logout',{method:'POST'})}catch{}state.sessionId=newSessionId();persist();showLogin()}
function showAnalysisWorkspace(){state.currentDashboardId=null;$('dashboardView').classList.add('hidden');$('composerWrap').classList.remove('hidden')}
function resetView(){state.runId=null;state.savedAnalysisId=null;state.result=null;if(state.eventSource)state.eventSource.close();showAnalysisWorkspace();$('welcomePanel').classList.remove('hidden');$('conversationView').classList.add('hidden');$('resultView').classList.add('hidden');$('stepList').innerHTML='';$('queryInput').value='';$('sendButton').disabled=state.quotaRemaining===0}
async function submitQuery(query){query=query.trim();if(state.quotaRemaining===0)return toast('本次体验的 2 次提问已全部使用完');if(!query||state.runId)return;showAnalysisWorkspace();state.savedAnalysisId=null;$('welcomePanel').classList.add('hidden');$('conversationView').classList.remove('hidden');$('resultView').classList.add('hidden');$('runCard').classList.remove('hidden');$('userMessage').textContent=query;$('stepList').innerHTML='';$('runStatus').textContent='正在创建任务';$('sendButton').disabled=true;const chartChoice=$('generateChart').checked?true:null;try{const created=await api('/api/chat',{method:'POST',body:JSON.stringify({query,session_id:state.sessionId,enable_long_term:false,generate_chart:chartChoice})});state.runId=created.run_id;showQuota(created.quota);connectEvents(created.events_url)}catch(error){showError(error.message);state.runId=null;$('sendButton').disabled=state.quotaRemaining===0}}
function connectEvents(url){if(state.eventSource)state.eventSource.close();const source=new EventSource(url);state.eventSource=source;const receive=event=>{const payload=JSON.parse(event.data);updateStep(payload);if(['completed','failed','cancelled'].includes(payload.event)){source.close();loadResult()}};['queued','started','progress','cancel_requested','completed','failed','cancelled'].forEach(name=>source.addEventListener(name,receive));source.onerror=()=>{source.close();if(state.runId)setTimeout(()=>pollRun(),800)}}
function updateStep(event){$('runStatus').textContent=event.message;let el=document.querySelector(`[data-node="${event.node}"]`);if(!el){el=document.createElement('div');el.dataset.node=event.node;$('stepList').append(el)}el.className=`step ${event.status}`;el.innerHTML=`<b>${escapeHtml(labels[event.node]||event.node)}</b>${escapeHtml(event.message)}`}
async function pollRun(){if(!state.runId)return;try{const run=await api(`/api/runs/${state.runId}`);if(['completed','failed','cancelled'].includes(run.status)){renderRun(run)}else setTimeout(pollRun,1000)}catch(error){showError(error.message)}}
async function loadResult(){if(!state.runId)return;try{renderRun(await api(`/api/runs/${state.runId}`))}catch(error){showError(error.message)}}
function renderRun(run){state.runId=null;state.savedAnalysisId=null;$('sendButton').disabled=state.quotaRemaining===0;if(run.status==='completed'&&run.result){state.result=run.result;$('runCard').classList.add('hidden');renderResult(run.result);loadConversations()}else showError(run.error?.message||`任务${run.status==='cancelled'?'已取消':'未完成'}`)}
function renderResult(result){state.result=result;$('resultView').classList.remove('hidden');$('answerText').textContent=result.answer||'分析完成。';const scope=result.scope||{};const drill=scope.drilldown;$('scopeLine').textContent=[scope.database,scope.row_count!=null?`共 ${scope.row_count} 行`:null,scope.truncated?'结果已截断':null,drill?(drill.direction==='up'?'上卷分析':'下钻分析'):null].filter(Boolean).join(' · ');$('saveAnalysisButton').disabled=!result.run_id||Boolean(state.savedAnalysisId);$('saveAnalysisButton').textContent=state.savedAnalysisId?'✓ 已保存':'☆ 保存分析';$('addDashboardButton').disabled=!result.run_id&&!state.savedAnalysisId;$('addDashboardButton').textContent='▦ 添加到仪表盘';$('downloadChartButton').disabled=!(result.charts||[]).length;renderAgentTrace(result.agent_trace||[]);renderInsights(result.insights||[]);renderTable(result.table||{});renderSql(result.sql||{});renderFollowups(result.suggested_questions||[]);renderDrillActions(scope.drill_actions||[]);renderChart((result.charts||[])[0])}
function renderAgentTrace(items){const panel=$('agentTracePanel');const list=$('agentTraceList');list.innerHTML='';panel.classList.toggle('hidden',!items.length);items.forEach(item=>{const card=document.createElement('div');card.className=`agent-trace-step ${item.status||'completed'}`;const details=item.details||{};const plans=Array.isArray(details.steps)?details.steps:[];card.innerHTML=`<div class="trace-step-head"><span class="trace-check">${item.status==='failed'?'!':'✓'}</span><div><strong>${escapeHtml(item.label||labels[item.node]||item.node)}</strong><small>${escapeHtml(item.message||'已完成')}</small></div></div>${plans.length?`<ol class="trace-plan">${plans.map(plan=>`<li><span>${escapeHtml(plan.operation||'执行数据查询')}</span>${plan.output?`<em>输出：${escapeHtml(plan.output)}</em>`:''}</li>`).join('')}</ol>`:''}`;list.append(card)})}
function renderInsights(items){const grid=$('insightGrid');grid.innerHTML='';items.slice(0,6).forEach((item,index)=>{const card=document.createElement('article');card.className='insight';card.innerHTML=`<span>INSIGHT ${String(index+1).padStart(2,'0')}</span><strong>${escapeHtml(item.title||item.type||'数据洞察')}</strong><p>${escapeHtml(item.text||item.description||item.message||item.value||'')}</p>`;grid.append(card)});grid.classList.toggle('hidden',!items.length)}
function renderTable(table){const columns=table.columns||[];const rows=table.rows||[];$('rowCount').textContent=`展示 ${rows.length} 行`;$('resultTable').innerHTML=`<thead><tr>${columns.map(c=>`<th>${escapeHtml(c)}</th>`).join('')}</tr></thead><tbody>${rows.slice(0,100).map(row=>`<tr>${columns.map((c,i)=>`<td>${escapeHtml(Array.isArray(row)?row[i]:row[c])}</td>`).join('')}</tr>`).join('')}</tbody>`}
function renderSql(sql){$('sqlCode').textContent=sql.text||'-- 本次问答未查询数据库';$('sqlMeta').textContent=[sql.dialect,sql.duration_ms!=null?`${sql.duration_ms} ms`:null].filter(Boolean).join(' · ')}
function renderFollowups(items){const box=$('followups');box.innerHTML=items.slice(0,4).map(q=>`<button data-followup="${escapeHtml(q)}">${escapeHtml(q)}</button>`).join('');box.querySelectorAll('button').forEach(button=>button.addEventListener('click',()=>{$('queryInput').value=button.dataset.followup;$('queryInput').focus()}))}
function renderDrillActions(items){const panel=$('drillPanel');const box=$('drillActions');box.innerHTML='';panel.classList.toggle('hidden',!items.length);items.forEach(action=>{const button=document.createElement('button');button.className='drill-action';button.innerHTML=`<span class="drill-direction">${action.direction==='up'?'↑':'↓'}</span>${escapeHtml(action.label)}`;button.onclick=()=>submitDrilldown(action);box.append(button)})}
async function submitDrilldown(action){if(state.quotaRemaining===0)return toast('本次体验的 2 次提问已全部使用完');const parentRunId=state.result?.run_id;if(!parentRunId)return toast('当前结果无法继续钻取');showAnalysisWorkspace();state.savedAnalysisId=null;$('welcomePanel').classList.add('hidden');$('conversationView').classList.remove('hidden');$('resultView').classList.add('hidden');$('runCard').classList.remove('hidden');$('cancelButton').classList.remove('hidden');$('userMessage').textContent=action.label;$('stepList').innerHTML='';$('runStatus').textContent=action.direction==='up'?'正在上卷分析':'正在下钻分析';$('sendButton').disabled=true;try{const created=await api('/api/drilldown',{method:'POST',body:JSON.stringify({parent_run_id:parentRunId,query:action.query,direction:action.direction,generate_chart:null})});state.runId=created.run_id;showQuota(created.quota);connectEvents(created.events_url)}catch(error){showError(error.message)}}
function renderChart(chart){const panel=$('chartPanel');if(!chart){panel.classList.add('hidden');return}panel.classList.remove('hidden');$('chartTitle').textContent=chart.title||'数据可视化';const option=chart.option||chart.echarts_option||chart;requestAnimationFrame(()=>drawCanvasChart(option,$('chartCanvas')))}
function formatChartNumber(value){return Number(value||0).toLocaleString('zh-CN',{maximumFractionDigits:2})}
function niceAxisMax(value){const rough=Math.max(Number(value)||1,1)*1.15;const magnitude=10**Math.floor(Math.log10(rough));const normalized=rough/magnitude;const step=normalized<=1?1:normalized<=2?2:normalized<=2.5?2.5:normalized<=5?5:10;return step*magnitude}
function drawCanvasChart(option,canvas){const rect=canvas.getBoundingClientRect();const ratio=window.devicePixelRatio||1;const series=(option.series||[])[0]||{};const raw=series.data||[];const values=raw.map(v=>Number(typeof v==='object'?(v.value??0):v)||0);const bundledCategories=raw.every(v=>typeof v==='object'&&v!==null&&v.name!=null);const categories=bundledCategories?raw.map(v=>v.name):((option.orientation==='horizontal'?option.yAxis?.data:option.xAxis?.data)||raw.map((v,i)=>i+1));const horizontal=option.orientation==='horizontal';const displayHeight=horizontal?Math.max(320,values.length*28+58):300;canvas.style.height=`${displayHeight}px`;canvas.style.maxHeight=`${displayHeight}px`;canvas.width=rect.width*ratio;canvas.height=displayHeight*ratio;const ctx=canvas.getContext('2d');ctx.scale(ratio,ratio);const w=rect.width,h=displayHeight;if(!values.length)return;if(horizontal){const pad={l:170,r:72,t:22,b:36},plotW=w-pad.l-pad.r,plotH=h-pad.t-pad.b,bandH=plotH/values.length,axisMax=niceAxisMax(Math.max(...values,1));ctx.clearRect(0,0,w,h);ctx.strokeStyle='#e9ecf2';ctx.fillStyle='#8b93a3';ctx.font='10px sans-serif';ctx.textAlign='center';for(let i=0;i<=4;i++){const x=pad.l+plotW*i/4;ctx.beginPath();ctx.moveTo(x,pad.t);ctx.lineTo(x,h-pad.b);ctx.stroke();ctx.fillText(formatChartNumber(axisMax*i/4),x,h-14)}values.forEach((v,i)=>{const y=pad.t+bandH*(i+.5),barH=Math.max(8,Math.min(18,bandH*.62)),barW=v/axisMax*plotW;ctx.fillStyle='#6075ed';ctx.fillRect(pad.l,y-barH/2,barW,barH);ctx.fillStyle='#526075';ctx.font='600 10px sans-serif';ctx.textAlign='right';ctx.fillText(String(categories[i]).slice(0,22),pad.l-10,y+3);ctx.textAlign='left';ctx.fillText(formatChartNumber(v),Math.min(w-pad.r+5,pad.l+barW+7),y+3)});return}const pad={l:66,r:24,t:34,b:48};ctx.clearRect(0,0,w,h);const axisMax=niceAxisMax(Math.max(...values,1)),plotW=w-pad.l-pad.r,plotH=h-pad.t-pad.b,bandW=plotW/values.length;ctx.strokeStyle='#e9ecf2';ctx.fillStyle='#8b93a3';ctx.font='10px sans-serif';ctx.textAlign='right';for(let i=0;i<=4;i++){const y=pad.t+plotH*i/4;ctx.beginPath();ctx.moveTo(pad.l,y);ctx.lineTo(w-pad.r,y);ctx.stroke();ctx.fillText(formatChartNumber(axisMax*(4-i)/4),pad.l-8,y+3)}const bar=series.type==='bar';ctx.strokeStyle='#5269ec';ctx.fillStyle='#6075ed';ctx.lineWidth=2.2;ctx.beginPath();values.forEach((v,i)=>{const x=pad.l+bandW*(i+.5);const y=pad.t+plotH-(v/axisMax)*plotH;if(bar){const bw=Math.max(8,Math.min(48,bandW*.55));ctx.fillRect(x-bw/2,y,bw,pad.t+plotH-y)}else{i?ctx.lineTo(x,y):ctx.moveTo(x,y)}});if(!bar)ctx.stroke();values.forEach((v,i)=>{const x=pad.l+bandW*(i+.5);const y=pad.t+plotH-(v/axisMax)*plotH;if(!bar){ctx.fillStyle='#6075ed';ctx.beginPath();ctx.arc(x,y,3,0,Math.PI*2);ctx.fill()}ctx.fillStyle='#526075';ctx.font='600 10px sans-serif';ctx.textAlign='center';ctx.fillText(formatChartNumber(v),x,Math.max(12,y-8));if(i%Math.ceil(values.length/8)===0){ctx.fillStyle='#8b93a3';ctx.font='10px sans-serif';ctx.fillText(String(categories[i]).slice(0,9),x,h-22)}})}
function showError(message){$('runStatus').textContent=message;$('runCard').classList.remove('hidden');$('cancelButton').classList.add('hidden');toast(message);state.runId=null;$('sendButton').disabled=state.quotaRemaining===0}
async function cancelRun(){if(!state.runId)return;try{await api(`/api/runs/${state.runId}/cancel`,{method:'POST'});$('runStatus').textContent='正在取消…'}catch(error){toast(error.message)}}
async function loadConversations(){try{const data=await api('/api/conversations');const list=$('conversationList');list.innerHTML=data.items.length?'':'<div class="empty-nav">还没有历史分析</div>';data.items.forEach(item=>{const button=document.createElement('button');button.className=`conversation-item ${item.session_id===state.sessionId?'active':''}`;button.textContent=item.title;button.onclick=()=>{state.sessionId=item.session_id;persist();loadConversation(item.session_id)};list.append(button)})}catch{}}
async function loadConversation(sessionId){try{showAnalysisWorkspace();state.savedAnalysisId=null;const data=await api(`/api/conversations/${encodeURIComponent(sessionId)}`);const assistant=[...data.items].reverse().find(m=>m.role==='assistant'&&m.payload&&Object.keys(m.payload).length);const user=[...data.items].reverse().find(m=>m.role==='user');if(user){$('welcomePanel').classList.add('hidden');$('conversationView').classList.remove('hidden');$('userMessage').textContent=user.content;$('runCard').classList.add('hidden');if(assistant)renderResult(assistant.payload)}loadConversations()}catch(error){toast(error.message)}}
async function saveAnalysis(){const runId=state.result?.run_id;if(!runId){toast('当前结果无法保存');return null}const button=$('saveAnalysisButton');button.disabled=true;button.textContent='保存中…';try{const saved=await api('/api/analyses',{method:'POST',body:JSON.stringify({run_id:runId,title:$('userMessage').textContent.trim().slice(0,120)})});state.savedAnalysisId=saved.id;button.textContent='✓ 已保存';toast('分析结果已保存');loadSavedAnalyses();return saved}catch(error){button.disabled=false;button.textContent='☆ 保存分析';toast(error.message);return null}}
function downloadResult(format){const runId=state.result?.run_id;if(!runId&&!state.savedAnalysisId)return toast('当前结果无法下载');const base=state.savedAnalysisId?`/api/analyses/${encodeURIComponent(state.savedAnalysisId)}`:`/api/runs/${encodeURIComponent(runId)}`;const link=document.createElement('a');link.href=`${base}/export.${format}`;link.download='';document.body.append(link);link.click();link.remove()}
function downloadChart(){const source=$('chartCanvas');if($('chartPanel').classList.contains('hidden')||!source.width)return toast('当前结果没有可下载的图表');try{const ratio=window.devicePixelRatio||1;const titleHeight=Math.round(54*ratio);const output=document.createElement('canvas');output.width=source.width;output.height=source.height+titleHeight;const ctx=output.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,output.width,output.height);ctx.fillStyle='#172033';ctx.font=`600 ${18*ratio}px sans-serif`;ctx.fillText(($('chartTitle').textContent||'问数分析图表').slice(0,80),Math.round(22*ratio),Math.round(34*ratio));ctx.drawImage(source,0,titleHeight);const link=document.createElement('a');const title=($('chartTitle').textContent||'问数分析图表').replace(/[^\u4e00-\u9fa5\w-]+/g,'_');link.href=output.toDataURL('image/png');link.download=`${title}.png`;link.style.display='none';document.body.append(link);link.click();link.remove();toast('图表 PNG 已开始下载')}catch(error){toast('图表下载失败，请允许浏览器下载后重试')}}
async function loadSavedAnalyses(){try{const data=await api('/api/analyses');const list=$('savedAnalysisList');list.innerHTML=data.items.length?'':'<div class="empty-nav">还没有保存结果</div>';data.items.forEach(item=>{const row=document.createElement('div');row.className='saved-analysis-item';const button=document.createElement('button');button.className='saved-analysis-open';button.textContent=item.title;button.title=item.query;button.onclick=()=>loadSavedAnalysis(item.id);const remove=document.createElement('button');remove.className='saved-analysis-delete';remove.textContent='×';remove.setAttribute('aria-label',`删除 ${item.title}`);remove.onclick=()=>deleteSavedAnalysis(item.id);row.append(button,remove);list.append(row)})}catch{}}
async function loadSavedAnalysis(analysisId){try{showAnalysisWorkspace();const item=await api(`/api/analyses/${encodeURIComponent(analysisId)}`);state.savedAnalysisId=item.id;state.sessionId=item.session_id;persist();$('welcomePanel').classList.add('hidden');$('conversationView').classList.remove('hidden');$('runCard').classList.add('hidden');$('userMessage').textContent=item.query;renderResult(item.result);loadConversations()}catch(error){toast(error.message)}}
async function deleteSavedAnalysis(analysisId){try{await api(`/api/analyses/${encodeURIComponent(analysisId)}`,{method:'DELETE'});toast('已删除保存记录');loadSavedAnalyses()}catch(error){toast(error.message)}}
async function loadDashboards(){try{const data=await api('/api/dashboards');state.dashboards=data.items||[];$('dashboardCount').textContent=state.dashboards.reduce((sum,item)=>sum+Number(item.card_count||0),0);return state.dashboards}catch{return []}}
async function ensureDefaultDashboard(){const items=await loadDashboards();if(items.length)return items[0];const created=await api('/api/dashboards',{method:'POST',body:JSON.stringify({name:'我的仪表盘',description:'集中查看保存的数据洞察。'})});await loadDashboards();return created}
async function openDashboard(dashboardId){try{let selected=dashboardId?state.dashboards.find(item=>item.id===dashboardId):state.dashboards[0];if(!selected)selected=await ensureDefaultDashboard();const dashboard=await api(`/api/dashboards/${encodeURIComponent(selected.id)}`);state.currentDashboardId=dashboard.id;$('welcomePanel').classList.add('hidden');$('conversationView').classList.add('hidden');$('composerWrap').classList.add('hidden');$('dashboardView').classList.remove('hidden');renderDashboard(dashboard)}catch(error){toast(error.message)}}
function renderDashboard(dashboard){$('dashboardTitle').textContent=dashboard.name;$('dashboardDescription').textContent=dashboard.description||'集中查看保存的数据洞察。';const grid=$('dashboardGrid');const cards=dashboard.cards||[];grid.innerHTML='';$('dashboardEmpty').classList.toggle('hidden',Boolean(cards.length));cards.forEach(card=>{const result=card.result||{};const article=document.createElement('article');article.className='dashboard-card';article.innerHTML=`<div class="dashboard-card-head"><span class="section-kicker">SAVED INSIGHT</span><button class="dashboard-card-remove" aria-label="移除卡片">×</button></div><h3>${escapeHtml(card.title)}</h3><p class="dashboard-card-answer">${escapeHtml(result.answer||'分析已完成')}</p><div class="dashboard-card-body"></div><div class="dashboard-card-foot"><button class="result-action dashboard-card-open">查看完整分析</button><span>${escapeHtml(card.analysis_updated_at?.slice(0,10)||'')}</span></div>`;const body=article.querySelector('.dashboard-card-body');const chart=(result.charts||[])[0];if(chart){const canvas=document.createElement('canvas');canvas.height=190;body.append(canvas);requestAnimationFrame(()=>drawCanvasChart(chart.option||chart.echarts_option||chart,canvas))}else{const insights=(result.insights||[]).slice(0,2);if(insights.length)body.innerHTML=insights.map(item=>`<div class="dashboard-kpi"><strong>${escapeHtml(item.title||item.type||'数据洞察')}</strong><span>${escapeHtml(item.text||item.description||item.value||'')}</span></div>`).join('');else{const rows=result.table?.rows||[];body.innerHTML=`<div class="dashboard-kpi"><strong>${rows.length}</strong><span>结果数据行</span></div>`}}article.querySelector('.dashboard-card-open').onclick=()=>loadSavedAnalysis(card.analysis_id);article.querySelector('.dashboard-card-remove').onclick=()=>removeDashboardCard(dashboard.id,card.id);grid.append(article)})}
async function addResultToDashboard(){const button=$('addDashboardButton');button.disabled=true;button.textContent='正在添加…';try{if(!state.savedAnalysisId){const saved=await saveAnalysis();if(!saved){button.disabled=false;button.textContent='▦ 添加到仪表盘';return}}const dashboard=await ensureDefaultDashboard();await api(`/api/dashboards/${encodeURIComponent(dashboard.id)}/cards`,{method:'POST',body:JSON.stringify({analysis_id:state.savedAnalysisId,title:$('userMessage').textContent.trim().slice(0,120)})});toast('已添加到仪表盘');await loadDashboards();button.textContent='✓ 已添加'}catch(error){button.disabled=false;button.textContent='▦ 添加到仪表盘';toast(error.message)}}
async function removeDashboardCard(dashboardId,cardId){try{await api(`/api/dashboards/${encodeURIComponent(dashboardId)}/cards/${encodeURIComponent(cardId)}`,{method:'DELETE'});toast('已从仪表盘移除');await loadDashboards();openDashboard(dashboardId)}catch(error){toast(error.message)}}
async function deleteCurrentDashboard(){if(!state.currentDashboardId||!window.confirm('确定删除这个仪表盘吗？保存的分析不会被删除。'))return;try{await api(`/api/dashboards/${encodeURIComponent(state.currentDashboardId)}`,{method:'DELETE'});toast('仪表盘已删除');await loadDashboards();resetView()}catch(error){toast(error.message)}}
async function loadDataSourceStatus(){try{const status=await api('/api/data-source/status');$('dataSourceName').textContent=status.database||status.alias||'数据源';$('dataSourceMeta').textContent=`${String(status.database_type||'').toUpperCase()} · ${status.ready?(status.error?'使用上次 Schema':'只读已连接'):'未连接'}`;$('dataSourceDot').classList.toggle('error',!status.ready);$('dataSourceDot').classList.toggle('warning',Boolean(status.ready&&status.error));$('dataSourceStatus').title=status.ready?`${status.table_count||0} 张表 · ${status.column_count||0} 个字段${status.error?` · ${status.error}`:' · 已同步'}`:status.error||'数据源不可用';showQuota({limit:status.query_limit,remaining:status.query_remaining,unlimited:status.query_unlimited},false)}catch(error){$('dataSourceName').textContent='数据源不可用';$('dataSourceMeta').textContent='请联系管理员';$('dataSourceDot').classList.add('error')}}
async function syncDataSource(){const button=$('syncDataSourceButton');button.disabled=true;button.textContent='…';try{const status=await api('/api/data-source/sync',{method:'POST'});toast(`Schema 已同步：${status.table_count} 张表，${status.column_count} 个字段`);loadDataSourceStatus()}catch(error){toast(error.message);loadDataSourceStatus()}finally{button.disabled=false;button.textContent='↻'}}
$('chatForm').addEventListener('submit',event=>{event.preventDefault();submitQuery($('queryInput').value);$('queryInput').value=''})
$('queryInput').addEventListener('input',event=>{event.target.style.height='auto';event.target.style.height=`${Math.min(event.target.scrollHeight,130)}px`})
$('queryInput').addEventListener('keydown',event=>{if(event.key==='Enter'&&!event.shiftKey){event.preventDefault();$('chatForm').requestSubmit()}})
document.querySelectorAll('[data-query]').forEach(button=>button.addEventListener('click',()=>submitQuery(button.dataset.query)))
$('newChatButton').addEventListener('click',()=>{state.sessionId=newSessionId();persist();resetView();loadConversations()})
$('cancelButton').addEventListener('click',cancelRun)
$('copySql').addEventListener('click',()=>navigator.clipboard.writeText($('sqlCode').textContent).then(()=>toast('SQL 已复制')))
$('saveAnalysisButton').addEventListener('click',saveAnalysis)
$('addDashboardButton').addEventListener('click',addResultToDashboard)
$('dashboardButton').addEventListener('click',()=>openDashboard())
$('deleteDashboardButton').addEventListener('click',deleteCurrentDashboard)
$('downloadCsvButton').addEventListener('click',()=>downloadResult('csv'))
$('downloadExcelButton').addEventListener('click',()=>downloadResult('xlsx'))
$('downloadChartButton').addEventListener('click',downloadChart)
$('mobileMenu').addEventListener('click',()=>document.querySelector('.sidebar').classList.toggle('open'))
$('loginForm').addEventListener('submit',login)
$('logoutButton').addEventListener('click',logout)
$('testerModeButton').addEventListener('click',toggleTesterMode)
$('syncDataSourceButton').addEventListener('click',syncDataSource)
window.addEventListener('resize',()=>{if(state.result?.charts?.[0])renderChart(state.result.charts[0])})
persist();initializeAuth();
